version: "3"

services:
  nginx:
    image: nginx
    restart: always
    container_name: shanfu-nginx
    ports:
      - "80:80"
    depends_on:
      - shanfu-backend
      - shanfu-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      shanfu-network:

  shanfu-backend:
    image: isabelle1007/shanfu-backend-image:amd64
    restart: always
    container_name: shanfu-backend
    ports:
      - "4002:4002"
    networks:
      shanfu-network:

  shanfu-frontend:
    image:  isabelle1007/shanfu-frontend-image:amd64
    restart: always
    container_name: shanfu-frontend
    ports:
      - "5173:5173"
    networks:
      shanfu-network:

networks:
  shanfu-network:
    driver: bridge
